
Training (Loss: 4.2499, output_max: 62):   0%|          | 1/1000 [00:05<1:24:02,  5.05s/it]
Traceback (most recent call last):
  File "C:\Users\Danny Han\Desktop\alphazero-sudoku\PureMLP.py", line 148, in <module>
    main(model)
  File "C:\Users\Danny Han\Desktop\alphazero-sudoku\PureMLP.py", line 119, in main
    assert False
AssertionError
[0.01676259 0.00950777 0.01421916 0.01053166 0.01004521 0.01512354
 0.0202251  0.01384825 0.02407336 0.00991433 0.01595999 0.02304298
 0.01715428 0.01308736 0.02549318 0.0118694  0.01168589 0.02656847
 0.01140199 0.01819067 0.01125946 0.01307487 0.006957   0.02092379
 0.02319761 0.02398962 0.01297311 0.02592073 0.01657967 0.01704075
 0.01198022 0.0154308  0.01965958 0.01344998 0.00493447 0.0096542
 0.0083165  0.01918383 0.01699579 0.02323999 0.00785364 0.02588064
 0.01051329 0.00686565 0.01246029 0.00873842 0.01456712 0.01713461
 0.0074055  0.01401851 0.02016862 0.01423705 0.03223137 0.0220807
 0.01083129 0.02442956 0.01302437 0.01075826 0.01082404 0.01387689
 0.01540382 0.01142488 0.03470843 0.00709595]