Traceback (most recent call last):
  File "C:\Users\Danny Han\Desktop\alphazero-sudoku\main.py", line 43, in <module>
    main()
  File "C:\Users\Danny Han\Desktop\alphazero-sudoku\main.py", line 38, in main
    data = get_trajectories_multiprocessing(net, args, logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny Han\Desktop\alphazero-sudoku\Trajectories.py", line 75, in get_trajectories_multiprocessing
    set_start_method('fork', force=True)
  File "C:\Users\Danny Han\anaconda3\envs\ESE-5460_23\Lib\multiprocessing\context.py", line 251, in set_start_method
    self._actual_context = self.get_context(method)
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny Han\anaconda3\envs\ESE-5460_23\Lib\multiprocessing\context.py", line 243, in get_context
    return super().get_context(method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny Han\anaconda3\envs\ESE-5460_23\Lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'